UpLoad

diff --git a/DraceMap b/DraceMap
--- a/DraceMap
+++ b/DraceMap
@@ -41,10 +41,10 @@ exit
 }
 
 #Bebeku
-if [[ $EUID -ne 0 ]]; then
-	echo "ERROR! Run this script with root user!"
-	exit 1
-fi
+#if [[ $EUID -ne 0 ]]; then
+#	echo "ERROR! Run this script with root user!"
+#	exit 1
+#fi
 
 if [ -z "${DISPLAY:-}" ]; then
     echo -e "\e[1;31mThe script should be executed inside a X (graphical) session."$transparent""
@@ -69,16 +69,16 @@ echo -e $lightgreen'-- -- +=[(c) 2016-2017 | dracos-linux.org | Linuxsec.org | P
 echo -e $cyan'-- -- +=[ Author: Screetsec < Edo Maland >  ]=+ -- -- '
 echo -e " "
 
-if [ $(id -u) != "0" ]; then
-
-      echo [!]::[Check Dependencies] ;
-      sleep 2
-      echo [✔]::[Check User]: $USER ;
-      sleep 1
-      echo [x]::[not root]: you need to be [root] to run this script.;
-      echo ""
-   	  sleep 1
-	  exit
+#if [ $(id -u) != "0" ]; then
+#
+#      echo [!]::[Check Dependencies] ;
+#      sleep 2
+#      echo [✔]::[Check User]: $USER ;
+#      sleep 1
+#      echo [x]::[not root]: you need to be [root] to run this script.;
+#      echo ""
+#   	  sleep 1
+#	  exit
 
 
 else
@@ -113,8 +113,8 @@ else
    echo [x]::[warning]:this script require Nmap ;
    echo ""
    echo [!]::[please wait]: please install .... ;
-   apt-get update
-   apt-get install nmap
+   # apt-get update
+   # apt-get install nmap
    echo ""
    sleep 2
    exit
